add h/w 11
htmlacademy-javascript/1629397-keksobooking-23 pull request #12
Opened 2021-07-12 14:19 UTC by train-octarine

Привет!
Фильтр, кажется, получился прям не очень. Сильно перегруженный и по списку несколько раз проходится. Пока идей, как сделать изящнее, нет :(

2021-07-12 16:23 UTC, o-bender requested changes

2021-07-12 16:23 UTC, o-bender commented on js/src/filter.js
> +  if (adFeatures !== undefined) {
тут можно два варианта использовать:
```
if (adFeatures) {
  // так ты сможешь убедиться, что в adFeatures не лежит null, или False, или ещё какая ерунда которую js сможет привести к False
}
```
Или так:
```
// И тогда if вообще не нужен
(adFeatures || []).forEach((item) => {
      if (featuresList.includes(item)) {
        rank++;
      }
    });
```

2021-07-12 16:23 UTC, o-bender commented on js/src/map.js
> +  advertisements
Такое решение не пройдёт по критерию. Но вообще такой подход применяют. Это конвейерная обработка.
Ещё оч круто придумал с ранжированием по удобствам. Но вроде по критерию оно не нужно и до него домотаются) но если хочешь можешь оставить, мб проверяющий оценит, так же как и я:)
И в принципе если используешь ранжирование, то наверное имеет смысл ранжировать по всем полям, в т.ч. стоимость и т.д. Если ранжировать по всем полям, то опять же можно пройти за один цикл :)
Если убрать ранжирование то, проход за один цикл будет выглядеть так:
```
advertisements.then(() => {
   const data = ads.slice();
   const output = [];
   for (const ad of data) {
       const isValid = filterHousingType(ad) &&
                               filterHousingPrice(ad) && 
                               filterHousingRooms(ad) && 
                               filterHousingGuests(ad) &&
                               // если выберешь этот вариант, то getFeaturesRank стоит переименовать в  filterHousingFeatures
                               getFeaturesRank(ad);
       if (isValid) {
           output.push(ad);
           if (output.length >= ADVERTISMENT_COUNT) {
               break;
           }
       }
   }
})
```

2021-07-12 16:23 UTC, o-bender commented on js/src/filter.js
> +const getFeaturesArray = () => {
тут можно сделать так:
```
const housingFeaturesFilterInputs = Array.from(mapFilters.querySelectorAll('input:checked')).map((element) => element.value);
```

2021-07-12 20:32 UTC, train-octarine commented on js/src/map.js
> +  advertisements
Увы,ранжирование придумал не я :)
Про это рассказывали на лайве и есть демонстрация на основе обучающего проекта. Не смог придумать как сделать функцию с фильтрованием удобств, поэтому сделал через сортировку.

2021-07-12 21:01 UTC, train-octarine commented
Попытался сделать всё через ранжирование, однако, работает плохо. Посмотри, пожалуйста, где ошибся.

2021-07-13 07:07 UTC, o-bender commented on js/src/filter.js
> +  if (filterHousingType(ad)) {
что бы не писать кучу if-ов можно сделать так:
```
  rank += [
    filterHousingType(ad),
    filterHousingPrice(ad),
    filterHousingRooms(ad),
    filterHousingGuests(ad),
  ].filter(Boolean).length * 10;
```

2021-07-14 06:55 UTC, merged